# Generated by Django 5.1.7 on 2025-03-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="access_date",
            field=models.DateTimeField(),
        ),
    ]
